# Header
menu:
    Home: /
    Archives: /archives
    rss: /atom.xml

random_amount: 5
per_page: 2

# Set image
img:
    logo: /img/logo.png
    avatar: /img/avatar.png
    daily_pic: /img/daily_pic.png
    sidebar_header: /img/sidebar_header.png
    footerico: /img/footer/footer_ico-
    upyun_logo: /img/upyun_logo.png
    random_thumbnail: /img/random/
