# Head
head:
    favicon: "/img/favicon.png"
    high_res_favicon: "/img/favicon.png"
    apple_touch_icon: "/img/favicon.png"
    keywords: 

# URL
url:
    about: #"/about"
    rss: 
    daily_pic: "#"
    logo: 

# Style
style:
    scheme: Nexus
    #scheme: Isolation

# UI & UX
uiux:
    slogan: "Hi, nice to meet you"
    theme_color: "#039BE5"
    theme_sub_color: "#00BCD4"
    hyperlink_color: "#039BE5"
    android_chrome_color: "#039BE5"
    fade_effect: true
    nprogress_color: "#FF4081"
    nprogress_buffer: "800"

# Reading
reading:
    markdown: Github
    entry_excerpt: 80

# Thumbnail settings
thumbnail:
    purecolor: 
    random_amount: 5

# Background settings
background:
    purecolor: "#F5F5F5"
    bgimg: "/img/bg.png"

# Image
img:
    logo: "/img/logo.png"
    avatar: "/img/avatar.png"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    upyun_logo: #"/img/upyun_logo.png"
    random_thumbnail: "/img/random/"

# SNS
sns:
    email: 
    twitter: "https://twitter.com/twitter"
    facebook: "https://www.facebook.com/facebook"
    googleplus: "https://www.google.com/"
    weibo: 
    instagram: 
    tumblr: 
    github: 

# Pages
pages:
    


# ---------------------------------------------------------------
# Third Party Services
# ---------------------------------------------------------------
    
# Comment
comment:
    use: 
    shortname: 
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    
# Leancloud Views
leancloud:
    enable: false
    app_id: #你的app_id
    app_key: #你的app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"
    
# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
